# Controls when the action will run.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Appium Server Action
        # You may pin to the exact commit or the version.
        # uses: moatazeldebsy/Appium-Server-GitHub-Action@05d9d683e555e7636d68a48360f1cf7c117ddda5
        uses: moatazeldebsy/Appium-Server-GitHub-Action@V1.0.5
        # Runs a single command using the runners shell
      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username:  'jayalakshmi_pRFSrh'
          access-key: 'oAxobBEwwz2rCtvjCa8A'
          build-name: 'Java Android'
          project-name: 'Test Appium framework'
      - name: Dependencies with Maven
        run: mvn clean install -DSkipTests
      - name: Test with Maven
        run: mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml